services:
  db:
    image: postgres:18-bookworm
    container_name: go-dailystep-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    restart: always

  db-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ./migrations:/migrations

volumes:
  postgres_data: